version: "3.9"
services:
  app:
    build:
      context: .
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      SECRET_KEY: "django-insecure-a6tt1(#u_gf*a8f4&c0i35qmf(4*ozm9w05pba(o)kw9p*s52$"
      PG_HOST: "postgres"
      PG_DB: "postgres"
      PG_USER: "postgres"
      PG_PASSWORD: "admin"
      PGADMIN_DEFAULT_EMAIL: "mikhailroot01@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"

  postgres:
    container_name: postgres
    image: postgres:14.6-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "82:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mikhailroot01@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    env_file:
      - .env
    depends_on:
      - postgres